<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Test.Shared</RootNamespace>
    <AssemblyName>Test.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Core" Version="0.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\S3Explorer\S3Explorer.csproj" />
  </ItemGroup>

</Project>
